# Generated by Django 4.0.3 on 2026-05-13 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulice', models.CharField(max_length=100)),
                ('psc', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Adresa',
                'verbose_name_plural': 'Adresy',
            },
        ),
        migrations.CreateModel(
            name='Restaurace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('adresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knihovna.adresa')),
            ],
            options={
                'verbose_name': 'Restaurace',
                'verbose_name_plural': 'Restaurace',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Stát',
                'verbose_name_plural': 'Státy',
            },
        ),
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('adresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knihovna.adresa')),
            ],
            options={
                'verbose_name': 'Zákazník',
                'verbose_name_plural': 'Zákazníci',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo', models.CharField(max_length=20)),
                ('restaurace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knihovna.restaurace')),
                ('zakaznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knihovna.zakaznik')),
            ],
            options={
                'verbose_name': 'Telefon',
                'verbose_name_plural': 'Telefony',
            },
        ),
        migrations.CreateModel(
            name='Stoly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo', models.IntegerField()),
                ('pocet_mist', models.IntegerField()),
                ('stav', models.CharField(choices=[('volny', 'Volný'), ('rezervovany', 'Rezervovaný'), ('obsazeny', 'Obsazený')], max_length=20)),
                ('Restaurace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knihovna.restaurace')),
            ],
            options={
                'verbose_name': 'Stůl',
                'verbose_name_plural': 'Stoly',
            },
        ),
        migrations.CreateModel(
            name='Rezervace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_cas', models.DateTimeField()),
                ('delka_trvani', models.DurationField()),
                ('pocet_osob', models.IntegerField()),
                ('poznamka', models.TextField(blank=True, null=True)),
                ('stul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knihovna.stoly')),
                ('zakaznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knihovna.zakaznik')),
            ],
            options={
                'verbose_name': 'Rezervace',
                'verbose_name_plural': 'Rezervace',
            },
        ),
        migrations.CreateModel(
            name='Oteviraci_doba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.CharField(choices=[('pondeli', 'Pondělí'), ('utery', 'Úterý'), ('streda', 'Středa'), ('ctvrtek', 'Čtvrtek'), ('patek', 'Pátek'), ('sobota', 'Sobota'), ('nedele', 'Neděle')], max_length=20)),
                ('otevreno_od', models.TimeField()),
                ('otevreno_do', models.TimeField()),
                ('Restaurace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knihovna.restaurace')),
            ],
            options={
                'verbose_name': 'Otevírací doba',
                'verbose_name_plural': 'Otevírací doby',
            },
        ),
        migrations.CreateModel(
            name='Mesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knihovna.stat')),
            ],
            options={
                'verbose_name': 'Město',
                'verbose_name_plural': 'Města',
            },
        ),
        migrations.AddField(
            model_name='adresa',
            name='mesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knihovna.mesto'),
        ),
    ]
