# Generated by Django 4.2 on 2026-06-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0003_alter_adresa_id_alter_mesto_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurace/'),
        ),
    ]
