# Generated by Django 4.2 on 2026-06-03 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knihovna', '0005_alter_adresa_id_alter_mesto_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaznik',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
