# Generated by Django 5.2 on 2026-06-04 07:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0006_zakaznik_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervace',
            name='datum_cas',
            field=models.DateTimeField(verbose_name=django.core.validators.MinValueValidator(limit_value=datetime.date(2026, 6, 4), message='Datum a čas rezervace musí být v budoucnosti.')),
        ),
        migrations.AlterField(
            model_name='rezervace',
            name='pocet_osob',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
