# Generated by Django 5.2 on 2026-06-04 07:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0007_alter_rezervace_datum_cas_alter_rezervace_pocet_osob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervace',
            name='datum_cas',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2026, 6, 4), message='Datum a čas rezervace musí být v budoucnosti.')]),
        ),
    ]
