# Generated by Django 5.2 on 2026-06-07 14:58

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0008_alter_rezervace_datum_cas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervace',
            name='datum_cas',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2026, 6, 7, 14, 58, 53, 659160, tzinfo=datetime.timezone.utc), message='Datum a čas rezervace musí být v budoucnosti.')]),
        ),
        migrations.AlterField(
            model_name='rezervace',
            name='stul',
            field=models.ForeignKey(limit_choices_to={'stav': 'volny'}, on_delete=django.db.models.deletion.CASCADE, to='knihovna.stoly'),
        ),
    ]
