# Generated by Django 5.2 on 2026-06-07 15:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0009_alter_rezervace_datum_cas_alter_rezervace_stul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervace',
            name='datum_cas',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2026, 6, 7, 15, 35, 55, 187312, tzinfo=datetime.timezone.utc), message='Datum a čas rezervace musí být v budoucnosti.')]),
        ),
    ]
