# Generated by Django 5.2 on 2026-06-07 15:48

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0012_alter_rezervace_datum_cas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervace',
            name='datum_cas',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2026, 6, 7, 15, 48, 9, 393991, tzinfo=datetime.timezone.utc), message='Datum a čas rezervace musí být v budoucnosti.')]),
        ),
        migrations.AlterField(
            model_name='rezervace',
            name='pocet_osob',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Počet osob musí být alespoň 1.')]),
        ),
        migrations.AlterField(
            model_name='rezervace',
            name='stul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knihovna.stoly'),
        ),
    ]
