# Generated by Django 5.2 on 2026-06-07 16:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0013_alter_rezervace_datum_cas_alter_rezervace_pocet_osob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervace',
            name='datum_cas',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2026, 6, 7, 16, 3, 8, 300196, tzinfo=datetime.timezone.utc), message='Datum a čas rezervace musí být v budoucnosti.')]),
        ),
    ]
