# Generated by Django 5.2 on 2026-06-07 16:26

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0014_alter_rezervace_datum_cas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresa',
            name='mesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knihovna.mesto', validators=[django.core.validators.RegexValidator('^[A-Za-zÁČĎÉĚÍŇÓŘŠŤÚŮÝŽáčďéěíňóřšťúůýž ]+$', 'Město může obsahovat pouze písmena.')]),
        ),
        migrations.AlterField(
            model_name='adresa',
            name='psc',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Nesprávně zadané poštovní směrovací číslo')]),
        ),
        migrations.AlterField(
            model_name='rezervace',
            name='datum_cas',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2026, 6, 7, 16, 26, 18, 256800, tzinfo=datetime.timezone.utc), message='Datum a čas rezervace musí být v budoucnosti.')]),
        ),
        migrations.AlterField(
            model_name='telefon',
            name='zakaznik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knihovna.zakaznik', validators=[django.core.validators.RegexValidator('^[+]\\d{3}( \\d{3}){3}$', 'Nesprávně zadané telefonní číslo')]),
        ),
    ]
